spring:
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb://admin:123456@123.57.63.140:27017/studyplan
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB

wechat:
  sessionHost: https://api.weixin.qq.com/sns/jscode2session
  appId: wxc2455722e0f21529
  secret: 21934bcd3df3b1704fc0f6f14b8e8211
  grantType: authorization_code
