spring:
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb://normal:123456@123.57.63.140:27017/studyplan
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB

wechat:
  sessionHost: https://api.weixin.qq.com/sns/jscode2session
  appId: wx9134da82420b59ee
  secret: 51ca797878678f637160a50b0d699b26
  grantType: authorization_code
